include("${CMAKE_CURRENT_LIST_DIR}/lib.cmake")

use_fixture(groups)
install_test_node("demo/bin")
# a group named like a node type, so one name means two things
file(WRITE "${SCRATCH}/sensor.hcl" "group {\n  node \"one\" {\n    type = \"demo/sensor\"\n  }\n}\n")

# Every kind word works singular, plural or short.
foreach(word package packages pkg pkgs)
  rant(ls ${word})
  expect_match("${OUT}" "^PACKAGES\n  demo +rant[.]hcl +no Rant +demo\n$")
endforeach()
rant(ls types)
expect_match("${OUT}" "NODE TYPES\n  demo/sensor +declared +")
rant(ls group)
expect_match("${OUT}" "  nav +speed=1 range=30 +Drive around\n")
rant(ls groups p)
expect_match("${OUT}" "^GROUPS\n  pick")
expect_no_match("${OUT}" "nav")
rant(ls types --json)
expect_match("${OUT}" "\"name\": \"demo/sensor\"")
rant(ls node)
expect_match("${OUT}" "^NODES\n  [(]none[)]\n$")
rant(ls nodes a b FAILS)
expect_match("${ERR}" "ls takes a kind and one pattern at most")

# info explains workspace things, and says when a name means more than one.
rant(info package demo)
expect_match("${OUT}" "^package: demo\n")
expect_match("${OUT}" "types: +[[]demo/sensor, demo/test_node[]]")
rant(info group nav)
expect_match("${OUT}" "params:\n  speed: float, default 1\n  range: int, default 30\n")
expect_match("${OUT}" "nodes:\n  lidar: +demo/sensor\n")
rant(info sensor)
expect_match("${ERR}" "`sensor` names a type and a group, `rant info type sensor` shows only one")
expect_match("${OUT}" "^type: +demo/sensor\n")
expect_match("${OUT}" "groups: +[[]base, nav, pick, sensor[]]")
expect_match("${OUT}" "\ngroup: +sensor\n")
rant(info type sensor)
expect_no_match("${OUT}" "group:")
rant(info group nowhere FAILS)
expect_match("${ERR}" "no group named `nowhere`")
rant(info thing nav FAILS)
expect_match("${ERR}" "`thing` is no kind")
