# Writes OUTPUT, a C++ file holding every file under SOURCE as bytes, so the presets of
# rant new and the agent skill are part of the binary. Run with cmake -P.

file(GLOB_RECURSE files RELATIVE "${SOURCE}" "${SOURCE}/*")
list(SORT files)

set(arrays "")
set(entries "")
set(i 0)
foreach(rel IN LISTS files)
  file(READ "${SOURCE}/${rel}" hex HEX)
  string(LENGTH "${hex}" digits)
  math(EXPR size "${digits} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  # a trailing 0 keeps an empty file a legal array
  string(APPEND arrays "static const unsigned char f${i}[] = { ${bytes}0 };\n")
  string(APPEND entries "        { \"${rel}\", f${i}, ${size} },\n")
  math(EXPR i "${i} + 1")
endforeach()

file(WRITE "${OUTPUT}.tmp" "// Generated by cmake/embed_templates.cmake from templates/. Do not edit.
#include \"scaffold/builtin.hpp\"

namespace scaffold {

${arrays}
const std::vector<BuiltinFile>& builtin_files() {
    static const std::vector<BuiltinFile> files = {
${entries}    };
    return files;
}

}
")
# rewritten only when it changed, so an unchanged template rebuilds nothing
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
